Tank:
  base_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : 'TRACK_L'
    right_wheel : 'TRACK_R'
    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    wheel_separation : 0.44
    wheel_radius : 1.0
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier    : 1.0
    cmd_vel_timeout: 1.0
    enable_odom_tf: false
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 4.0
        min_velocity           : -4.0 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 6.28  # rad/s
        min_velocity           : -6.28
        has_acceleration_limits: true
        max_acceleration       : 1.57  # rad/s^2
        min_acceleration       : -1.57
